### ISSUE TITLE
Inquiry regarding project license

### ISSUE THREAD

**Issue by yilihjy** [hqwuzhaoyi/gpt-subtitle#30]
Hello @hqwuzhaoyi ,

I hope this message finds you well. I recently came across your project on GitHub and I must say, I am truly impressed by the work you have done. The project touches upon a subject that I find fascinating, and it showcases your technical prowess and creativity.

However, while exploring the code repository, I was unable to find any information regarding the open source license or project license.

I would like to inquire about the licensing arrangements for this project. Could you kindly provide some details regarding the project’s license? Specifically, I would appreciate knowing under which license the project is released and if there are any contributing guidelines to be mindful of.

Obtaining an understanding of the terms and conditions for using and familiarizing myself with this project would be of great help. Thank you for taking the time to address this query.

I appreciate your attention to this matter and I look forward to hearing from you soon.

Best regards

**Comment by hqwuzhaoyi** [comment]
@yilihjy Hello, yilihjy 😊
Thank you for your attention! I have added the `MIT License` to the project.
I sincerely hope that this project can be of help to you .
The project is still in its very initial stage, and there may be some issues. If you find any problems, please be understanding . We warmly welcome everyone to contribute and offer suggestions .
Looking forward to working with you to grow this project !
