### ISSUE TITLE
可以根據檔案內有沒有中文字幕判斷要不要翻譯嗎?

### ISSUE THREAD

**Issue by xiNeRoar** [hqwuzhaoyi/gpt-subtitle#341]
如題，可以設定成假如資料夾內已經存在中文字幕的話自動跳過嗎?

**Comment by hqwuzhaoyi** [comment]
感觉可以诶，这个我规划下，现在的自动任务处理还不是很完善👍👍👍

**Comment by hqwuzhaoyi** [comment]
> 如題，可以設定成假如資料夾內已經存在中文字幕的話自動跳過嗎?
添加了个新功能，可以根据字幕的语言后缀过滤出视频
中文的话，可以包括 xxx.zh.ass 类似的格式，还有chi、中这几种来筛选

![2024-03-31 01 13 08](https://github.com/hqwuzhaoyi/gpt-subtitle/assets/44605072/f508768f-6d1c-4484-9ae3-bc7aabbc5752)
