### ISSUE TITLE
npm run deploy:prod 失败

### ISSUE THREAD

**Issue by heidan123** [hqwuzhaoyi/gpt-subtitle#65]
`web:build: ./components/ui/alert-dialog.tsx
web:build: 24:17  Warning: 'children' is defined but never used. Allowed unused args must match /^_/u.  unused-imports/no-unused-vars
web:build: 
web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
web:build: - info Collecting page data...
web:build: - info Generating static pages (0/9)
web:build: - info Generating static pages (2/9)
web:build: Invalid URL
web:build: - info Generating static pages (4/9)
web:build: TypeError: fetch failed
web:build:     at Object.fetch (node:internal/deps/undici/undici:11576:11)
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
web:build:   cause: Error: connect ECONNREFUSED 127.0.0.1:3000
web:build:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1495:16)
web:build:       at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
web:build:     errno: -111,
web:build:     code: 'ECONNREFUSED',
web:build:     syscall: 'connect',
web:build:     address: '127.0.0.1',
web:build:     port: 3000
web:build:   }
web:build: }
web:build: - info Generating static pages (6/9)
web:build: imagePreview { visible: false, image: null }
web:build: 
web:build: Error occurred prerendering page "/preview/gallery". Read more: https://nextjs.org/docs/messages/prerender-error
web:build: TypeError: fetch failed
web:build:     at Object.fetch (node:internal/deps/undici/undici:11576:11)
web:build:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
web:build: imagePreview { visible: false, image: null }
web:build: - info Generating static pages (9/9)
web:build: 
web:build: > Export encountered errors on following paths:
web:build: 	/preview/gallery/page: /preview/gallery
web:build:  ELIFECYCLE  Command failed with exit code 1.
web:build: ERROR: command finished with error: command (/home/gpt-subtitle-master/apps/web) pnpm run build exited (1)
web#build: command (/home/gpt-subtitle-master/apps/web) pnpm run build exited (1)

 Tasks:    7 successful, 8 total
Cached:    7 cached, 8 total
  Time:    13.086s 
Failed:    web#build

 ERROR  run failed: command  exited (1)
`
npm run deploy:prod 的时候爆这个错误，是什么原因呀

**Comment by hqwuzhaoyi** [comment]
不好意思现在才看到，麻烦发下你的.env文件，是不是配置的环境变量不对，因为Next build需要 prerender，所以要正确配置数据库和环境变量才行

**Comment by hqwuzhaoyi** [comment]
您好，感谢您提出的问题。我已成功地复现该问题，并已进行了修复。您可以在以下 GitHub 提交中查看具体的更改：

[查看提交](https://github.com/hqwuzhaoyi/gpt-subtitle/commit/0de6aef56171d687acba5761d9eb724435323bd6)

该修复主要解决了在没有缓存的情况下打包失败的问题。

如果您有进一步的问题或疑惑，请随时联系我，您也可以直接通过电子邮件与我取得联系。

再次感谢您的提问和支持。

祝一切顺利！😁
