### ISSUE TITLE
URL 拼接错误，导致字幕无法下载

### ISSUE THREAD

**Issue by yann-y** [hqwuzhaoyi/gpt-subtitle#81]
gpt-subtitle/apps/server/src/subtitle/subtitle.service.ts:33
```
 return path.join(staticPath, relativePath);
```
这段代码拼接结果是 --> 'http:/localhost:3001/static/video/Apollo_11_moonwalk_montage_720p.srt'
url拼接不能使用path.join拼接，路径里面‘//’会被转换为‘/’。
我改为
```
return url.resolve(
        staticPath,
        relativePath
      );
```
拼接就正常了。这个页面的下载功能也正常了。
![image](https://github.com/hqwuzhaoyi/gpt-subtitle/assets/42291730/5ba08f9d-2403-4bcd-a493-cd63141379c4)

**Comment by hqwuzhaoyi** [comment]
您好，我非常感激您对本项目的使用，并且对您提出的问题和做出的修复表示深深的感谢。

现在项目还处于早期开发阶段，因此，如果您在使用本项目过程中遇到任何问题或者有任何的疑虑和不满，我热切希望您能够联系我。您可以随时与我取得联系，或者通过电子邮件与我直接沟通。

我再次对您提出的问题和您所给予的支持表达我最真诚的感激。衷心感谢您的宝贵意见和建议！

祝您在使用我们的产品过程中一切顺利，期待能够为您提供更多帮助！

如果有更多疑问或需要进一步的协助，欢迎随时与我联系。

谢谢！
