### ISSUE TITLE
這個項目跟chinesesubfinder有機會合作嗎？

### ISSUE THREAD

**Issue by xiNeRoar** [hqwuzhaoyi/gpt-subtitle#90]
如題 想知道跟https://github.com/ChineseSubFinder/ChineseSubFinder
有沒有合作連動的機會

然後如果一起使用的話會有問題嗎？

**Comment by hqwuzhaoyi** [comment]
你好，我也是 **ChineseSubFinder** 的用户，在日后的迭代过程中也我会思考是否能够配合使用，如果您有任何创意、想法或建议，我非常欢迎您提出来。让我们共同合作，使这个项目变得更加完善和强大。期待与您的交流与合作！

**Comment by xiNeRoar** [comment]
可能你誤會了 我不是作者只是一個普通用戶 單純好奇問問而已

**Comment by hqwuzhaoyi** [comment]
哈哈哈，没事，只是有想法都欢迎提出😆

> 可能你誤會了 我不是作者只是一個普通用戶 單純好奇問問而已
