### ISSUE TITLE
該如何映射jellyfin的媒體目錄?

### ISSUE THREAD

**Issue by xiNeRoar** [hqwuzhaoyi/gpt-subtitle#93]
假如jellyfin的媒體目錄是
media>movie>movie1, movie2, movie3, ...
請問該如何映射媒體路徑?
是該修改Static_path嗎?

OPENAI_API_KEY=` # OpenAI API KEY
GOOGLE_TRANSLATE_API_KEY= # Google API KEY(Can be left blank)
BASE_URL= # OpenAI API URL
WEB_PORT=3000 # Front-end port
SERVER_PORT=3001  # Backend port

STATIC_PATH=/static # Static file path
OUTPUT_SRT_THEN_TRANSLATE=true # Whether to output the SRT file first and then translate it
LANGUAGE=zh-CN # Output SRT file and then translate the language
TRANSLATE_DELAY=1500 # Delay between calling translation interface
TRANSLATE_GROUP=4 # Translate sentences for grouping translation, how many sentences can be translated at most at a time
TranslateModel=google # google or gpt3

REDIS_PORT=6379 # Redis port
REDIS_HOST=subtitle_redis # Redis address
MYSQL_HOST=subtitle_mysql # MySQL address
MYSQL_PORT=3306 # MySQL port
MYSQL_USER=root # MySQL user
MYSQL_PASSWORD=123456 # MySQL password
MYSQL_DATABASE=gpt_subtitle # MySQL Database name

API_URL=http://localhost:3001 # Backend API address
NEXT_PUBLIC_API_URL=http://localhost:3001 # Same as above. Backend API address
WEB_URL=http://localhost:3000 # Web address
NEXT_PUBLIC_WEB_URL=http://localhost:3000 # Same as above. WEB address

**Comment by hqwuzhaoyi** [comment]
你可以映射到 uploads/video 文件夹，比如像我下面这😁

![CleanShot 2023-09-28 at 16 45 37@2x](https://github.com/hqwuzhaoyi/gpt-subtitle/assets/44605072/da19dbda-f6d9-4665-a219-7b06ad88ebb1)

**Comment by hqwuzhaoyi** [comment]
.env 文件不会影响到文件路径。如果在使用过程中您遇到任何疑问或问题，我非常欢迎您随时与我取得联系，我会尽我所能为您提供帮助和支持。

**Comment by xiNeRoar** [comment]
好謝謝 我先試試看 因為有點看不太明白 謝謝你

**Comment by hqwuzhaoyi** [comment]
有任何问题或疑问，都欢迎您通过创建issue或发送电子邮件与我取得联系。我看到后会尽快给予回复。😁😁
2023年9月28日 +0800 21:05 xiNeRoar ***@***.***>，写道：

**Comment by xiNeRoar** [comment]
請問為什麼你的docker compose file裡面，subtitle_api跟subtitle_web都沒有指定image?
version: "3"

services:
  subtitle_api:
    container_name: subtitle_api
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    volumes:
      - /Users/wuzhaoyi/workspace/gpt-subtitle/uploads:/app/uploads
    ports:
      - 3001:3001
    networks:
      - subtitle_app_network
    env_file:
      - .env
    depends_on:
      - subtitle_mysql
      - subtitle_redis

  subtitle_web:
    container_name: subtitle_web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - WEB_PORT=3000
        - SERVER_PORT=3001
        - API_URL=http://localhost:3001
        - STATIC_PATH=/static
    restart: always
    ports:
      - 3000:3000
    networks:
      - subtitle_app_network
    env_file:
      - .env
    depends_on:
      - subtitle_api

  subtitle_mysql:
    container_name: subtitle_mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - subtitle_mysql_data:/var/lib/mysql
    networks:
      - subtitle_app_network
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  subtitle_redis:
    container_name: subtitle_redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - subtitle_app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  subtitle_app_network:

# Volume for MySQL
volumes:
  subtitle_mysql_data:

**Comment by xiNeRoar** [comment]
當我嘗試用portainer去deploy的時候一直跑出
failed to deploy a stack: Failed to load /data/compose/61/.env: open /data/compose/61/.env: no such file or directory
已經在portainer內upload了env 不知道發生了什麼事

**Comment by xiNeRoar** [comment]
嘗試了很多次用portainer去deploy; 
結果都跑出下面的error 沒法試用:(
failed to deploy a stack: listing workers for Build: failed to list workers: Unavailable: connection error: desc = "error reading server preface: http2: frame too large"

**Comment by hqwuzhaoyi** [comment]
因为这个项目使用了nextjs，需要根据env运行时打包，所以暂时portainer部署可能有点问题。可以在clone项目后，修改.env文件后，再运行 docker compose up -d
2023年9月28日 +0800 21:47 xiNeRoar ***@***.***>，写道：

**Comment by xiNeRoar** [comment]
好的我嘗試看看 謝謝

**Comment by xiNeRoar** [comment]
感覺能力有限 部署的過程中又出現了fail to build web 我想我還是等你的jellyfin plugin出來後再使用好了

**Comment by hqwuzhaoyi** [comment]
看着报错好像是存储空间满了

非常感谢您的关注与理解，我会在后续的更新中优化 Docker 的部署配置。

再次表示感谢，也很高兴看到您对本项目的尝试和使用，期望未来能够为您带来更加完善和优质的体验。
